### PR TITLE
bpf: bump prepend_name underlying buffer size 4096

### LINKED ISSUE #2758: matchBinaries `Prefix` operator fails to match path longer than 256 chars
The matchBinaries `Prefix` operator fails to match a path longer than 256 chars because of the way we read the binary path. We use the `exe` of the process and walk the dentry from end to beginning. Thus if the path is too long, the buffer contains an incorrect start.

A good situation looks like this:
```
 <--        buflen         -->
 -----------------------------
 |                /etc/passwd|
 -----------------------------
                 ^
                 |
                buf
 ```
 
 A bad situation looks like this:
```
 <- buflen ->
 -----------
 |tc/passwd|
 -----------
 error = 1
 ```

A permanent solution would be to increase the length `prepend_name` can work on. On a first attempt, it does not seem to be an issue. However, what is blocking is that `memcpy` and `memset` will fail on the larger struct (above 1K) even though we make sure those struct are not allocated on the stack (which is 512K).

### PR DESCRIPTION
**Pull request by mtardy**
Fixes #2758
### Description

The matchBinaries Prefix operator fails to match a path longer than 256 chars because of the way we read the binary path. We use the exe of the process and walk the dentry from end to beginning. Thus if the path is too long, the buffer contains an incorrect start.

### Changelog

```release-note
Fix a bug related to the matchBinaries Prefix operator by increasing the buffer size used by our dentry walk. Now the matchBinaries Prefix operator can correctly trigger a match on any path above 255 chars.
```

### CODE REVIEW

**Comment by mtardy** [comment]
cc @anfedotoff

**Comment by anfedotoff** [comment]
Nice! Thanks, @mtardy. It seems that I can close #2718 you already cherry-picked the test.

**Comment by mtardy** [comment]
> Nice! Thanks, @mtardy. It seems that I can close #2718 you already cherry-picked the test.

yeah I need to rework the test a little bit as well it seems to no work.

File: bpf/process/bpf_execve_event.c [hunk 1]
```diff
@@ -169,11 +169,18 @@ read_exe(struct task_struct *task, struct heap_exe *exe)
...
+	// matching on the prefix operators, even if we only keep a subset of that
+	char *buffer;
+
+	buffer = d_path_local(path, (int *)&exe->len, (int *)&exe->error);
+	if (!buffer)
+		return 0;
+
+	// buffer used by d_path_local can contain up to MAX_BUF_LEN i.e. 4096 we
+	// only keep the first 255 chars for our needs
+	exe->len &= 0xFF;
```
Comment (kevsecurity) [inline bpf/process/bpf_execve_event.c:182]: Masking to the lower 255 bits seems wrong. Surely if returned path is 257 in length, then masking it with 0xFF will make the length 1, instead of 255.

Comment (mtardy) [reply bpf/process/bpf_execve_event.c:182]: hehe you caught the bug I caught during the rhel8 investigation indeed what I wanted here, nice catch thanks!
```diff
-       exe->len &= 0xFF;
+       bpf_printk("exe before mask: %d", exe->len);
+       if (exe->len >= 256) {
+               exe->len = 256;
+       }
```

**Comment by mtardy** [comment]
I bumped into a rhel8 (rocky 8.6) bug, let's bump to a newer 8.9 that is fixed https://github.com/cilium/little-vm-helper-images/pull/612.

File: bpf/process/bpf_execve_event.c (hunk 1 above)
Comment (kevsecurity) [reply bpf/process/bpf_execve_event.c]: I think it should be exe->len = 255; (instead of 256) unless the comment is wrong?

**Comment by kevsecurity** [comment]
CI looks pretty red ❓

File: bpf/process/bpf_execve_event.c (hunk 1 above)
Comment (mtardy) [reply bpf/process/bpf_execve_event.c]: I bumped the comment, why would you take 255 instead of 256?

**Comment by mtardy** [comment]
> CI looks pretty red ❓

oh boy I just rebased and made the tiny change and indeed it seems everything is broken

File: bpf/process/bpf_execve_event.c (hunk 1 above)
Comment (kevsecurity) [reply bpf/process/bpf_execve_event.c]: It might not matter here, but often in BPF we set upper limits as one less than a power of two, so that we can do "&= MASK" type operations to constrain an index into the array (to satisfy the verifier as opposed to avoiding overflows). Maybe check that this buffer doesn't need this constraint?

Comment (mtardy) [reply bpf/process/bpf_execve_event.c]: Indeed I didn't check not sure why but this is what makes the verifier unhappy. It's unhappy mostly because `exe->len` seems to be possibly negative. If I add a naive `if v < 0; v = 0` it gets optimized out.

Comment (kevsecurity) [reply bpf/process/bpf_execve_event.c]: exe->len is a u32 so the compiler is absolutely sure it can't be <0 :D hence it gets rid of it. The verifier on the other hand isn't so sure (and rightly so).
Solution is something like:
```
if (exe->len > 255) {
    exe->len = 255;
}
asm volatile("%[len] &= 0xff;\n"
     : [len] "+r"(exe->len)
     :);
```
i.e. limit it to 255 to get the right logic, and then mask it to make the verifier happy, using "asm volatile" to force the compiler to insert it at this point.

Comment (mtardy) [reply bpf/process/bpf_execve_event.c]: Yes this way it works I tried but I lost 1 char, I tried to make it work with 256 :D

Comment (mtardy) [reply bpf/process/bpf_execve_event.c]: It seems that the inline asm is no longer needed, do you think we should continue use it like that?

Comment (kevsecurity) [reply bpf/process/bpf_execve_event.c]: You only need the inline asm if the verifier complains. It varies between kernel versions so 🤷 .

Comment (mtardy) [reply bpf/process/bpf_execve_event.c]: So apparently can:
- sacrifice 1 char to the verifier god and continue my day
- write a potentially broken bitwise operation on 32 bits and fight it

Comment (kevsecurity) [reply bpf/process/bpf_execve_event.c]: I think sacrificing 1 byte (which we do everywhere) is less complex and therefore easier to maintain.

File: bpf/process/bpf_execve_event.c [hunk 2]
```diff
@@ -180,11 +180,21 @@ read_exe(struct task_struct *task, struct heap_exe *exe)
...
+	char *buffer;
+
+	buffer = d_path_local(path, (int *)&exe->len, (int *)&exe->error);
+	if (!buffer)
+		return 0;
+
+	// buffer used by d_path_local can contain up to MAX_BUF_LEN i.e. 4096 we
+	// only keep the first 255 chars for our needs (we sacrifice one char to the
+	// verifier for the > 0 check)
+	if (exe->len >= 255)
```
Comment (kevsecurity) [inline bpf/process/bpf_execve_event.c:194]: nit: if exe->len == 255, you don't need to set it to 255

Comment (mtardy) [reply bpf/process/bpf_execve_event.c:194]: Ah yes it's not intentional

**Comment by kevsecurity** [comment]
I think you need ```make format```

**Review by kevsecurity — APPROVED** [review]
LGTM
