### PR TITLE
pkg/sensors: fix memory use of unloaded sensors

### LINKED ISSUE #3013: Disabled policies should update the tracing policy kernel memory consumption
Thanks to Anna for helping me see this issue.

_Originally posted by @lambdanis in https://github.com/cilium/tetragon/pull/2984#discussion_r1803875560_

### PR DESCRIPTION
**Pull request by mtardy**
Fixes #3013 

Sensors that are disabled are not loaded and should not use memory, thus we clear the LoadedMapsInfo on unloading programs.

### CODE REVIEW

**Comment by mtardy** [comment]
Regarding the metrics talked here https://github.com/cilium/tetragon/pull/2984#discussion_r1803875560, I think it still makes sense to report 0 for a disabled policy.

File: pkg/sensors/program/program.go [hunk 1]
```diff
@@ -206,6 +206,7 @@ func (p *Program) Unload() error {
 	}
 	p.unloader = nil
 	p.unloaderOverride = nil
+	p.LoadedMapsInfo = nil
```
Comment (mtardy) [inline pkg/sensors/program/program.go:209]: mmh just wait before merging, if the pinned is still there, this might be wrong to do that, I'll should check if ref are to 0 before considering that the maps have been removed.

Comment (mtardy) [reply pkg/sensors/program/program.go]: it should be good now, I just noticed that `--keep-sensors-on-exit` break disabling policies, but that's another issue.

**Review by lambdanis — APPROVED** [review]
