### PR TITLE
fix: incorrect default logger configuration

### LINKED ISSUE #4733: log level and format are not respected during the app start-up
### What happened? How can we reproduce this?

Actual: incorrect log records and/or in incorrect format produced
Expected: no such log records are produced

#### Environment
* k8s: EKS 1.32
* kernel: 6.1.159
* OS: Bottlerocket
* Tetragon args:

```shell
args:
  - --config-dir=/etc/tetragon/tetragon.conf.d/
  - --log-format=json
  - --log-level=WARN
```

#### Logs

<details>
  <summary>Logs produced</summary>

```shell
level=info msg="Loaded config from directory" config-dir=/etc/tetragon/tetragon.conf.d/
level=info msg="Starting gops server" addr=localhost:8118
level=info msg="Starting tetragon" version=v1.6.0
level=info msg="config settings" config="map[bpf-dir:tetragon bpf-lib:/var/lib/tetragon/ btf: cgroup-rate: cluster-name: config-dir:/etc/tetragon/tetragon.conf.d/ cpuprofile: cri-endpoint: data-cache-size:1024 debug:false disable-kprobe-multi:false enable-ancestors: enable-cgidmap:false enable-cgidmap-debug:false enable-cgtrackerid:true enable-compatibility-syscall64-size-type:false enable-cri:false enable-export-aggregation:false enable-k8s-api:true enable-msg-handling-latency:false enable-pid-set-filter:false enable-pod-annotations:true enable-pod-info:true enable-policy-filter:true enable-policy-filter-cgroup-map:true enable-policy-filter-debug:false enable-process-cred:true enable-process-ns:true enable-tracing-policy-crd:true event-cache-retries:15 event-cache-retry-delay:2 event-queue-size:10000 execve-map-entries:0 execve-map-size: export-aggregation-buffer-size:10000 export-aggregation-window-size:15s export-allowlist:{\"namespace\":[\"my-namespace\"], \"event_set\":[\"PROCESS_EXEC\", \"PROCESS_EXIT\", \"PROCESS_KPROBE\"]} export-denylist:{\"health_check\":true} export-file-compress:false export-file-max-backups:3 export-file-max-size-mb:100 export-file-perm:600 export-file-rotation-interval:0s export-filename:/var/run/cilium/tetragon/tetragon.log export-rate-limit:60000 expose-stack-addresses:false force-large-progs:false force-small-progs:false generate-docs:false gops-address:localhost:8118 health-server-address::6789 health-server-interval:10 k8s-controlplane-retry:1 k8s-kubeconfig-path: keep-sensors-on-exit:false kernel: log-format:json log-level:WARN memprofile: metrics-label-filter:namespace,workload metrics-server::2112 netns-dir:/var/run/docker/netns/ pprof-address: process-cache-gc-interval:30s process-cache-size:65536 procfs:/procRoot rb-queue-size:65535 rb-size:0 rb-size-total:0 redaction-filters: release-pinned-bpf:true server-address:localhost:54321 tracing-policy: tracing-policy-dir:/etc/tetragon/tetragon.tp.d use-perf-ring-buffer:false username-metadata:disabled verbose:0]"
level=info msg="Tetragon pid file creation succeeded" pid=3447 pidfile=/var/run/tetragon/tetragon.pid
level=info msg="BPF: successfully released pinned BPF programs and maps" bpf-dir=/sys/fs/bpf/tetragon
level=info msg="BPF detected features: override_return: true, buildid: true, kprobe_multi: false, uprobe_multi true, fmodret: true, fmodret_syscall: true, signal: true, large: true, link_pin: true, lsm: true, missed_stats_kprobe_multi: true, missed_stats_kprobe: true, batch_update: true, uprobe_refctroff: true, audit_loginuid: true probe_write_user: false uprobe_regs_change: false"
level=info msg="Updated TetragonConf map successfully" confmap-update=tg_conf_map deployment.mode=Kubernetes log.level=4 cgroup.fs.magic=Cgroupv2 cgroup.hierarchyID=0 NSPID=1
level=info msg="Enabling Kubernetes API"
level=info msg="Configured redaction filters" redactionFilters=""
level=info msg="Starting gRPC server" protocol=tcp address=localhost:54321
level=info msg="Configured field filters" fieldFilters="[fields:{paths:\"args\"  paths:\"parent\"  paths:\"process.arguments\"  paths:\"process.ns\"  paths:\"process.cap\"  paths:\"process.pod.pod_labels\"  paths:\"process.pod.pod_annotations\"  paths:\"process.process_credentials\"}  action:EXCLUDE]"
level=info msg="Starting JSON exporter" logger="&{Filename:/var/run/cilium/tetragon/tetragon.log MaxSize:100 MaxAge:0 MaxBackups:3 LocalTime:false Compress:false FileMode:-rw------- size:0 file:<nil> mu:{_:{} mu:{state:0 sema:0}} millCh:<nil> startMill:{_:{} done:{_:{} v:0} m:{_:{} mu:{state:0 sema:0}}}}" request="allow_list:{namespace:\"my-namespace\"  event_set:PROCESS_EXEC  event_set:PROCESS_EXIT  event_set:PROCESS_KPROBE}  deny_list:{health_check:{value:true}}"
level=info msg="Exporter configuration" enabled=true fileName=/var/run/cilium/tetragon/tetragon.log
level=info msg="Starting gRPC health server" address=:6789 interval=10
level=info msg="Enabling policy informers"
{"level":"warn","msg":"kprobe spec pre-validation issued a warning, but will continue with loading","policy":"my-namespace/file-monitoring-reads","sensor":"generic_kprobe","error":"validation warning: type (long unsigned int) of argument 2 does not match spec type (uint32)"}

```
</details>

Only the last log message is expected - JSON format + WARN log level.

**NOTE**: The "config settings" log record shows correct log configuration: `log-format:json log-level:WARN`, but we still see `info` logs in the `text` format.

### Tetragon Version

1.6.0

### Kernel Version

6.1.159

### Kubernetes Version

EKS 1.32

### PR DESCRIPTION
**Pull request by mann-ds**
Fixes #4733 

### Description
Update logging setup to reconfigure `DefaultSlogLogger` in place so cached logger pointers use the configured level and format.

### Changelog

```release-note
fix: startup logging to consistently honor configured log level and format
```

### CODE REVIEW

**Comment by FedeDP** [comment]
Ehy! Thanks for this! I already opened a (very!) similar fix as part of https://github.com/cilium/tetragon/pull/4378 (see first commit) :) 

WDYT?

**Comment by mann-ds** [comment]
> Ehy! Thanks for this! I already opened a (very!) similar fix as part of #4378 (see first commit) :)
> 
> WDYT?

Ah nice! Wish I saw this before, heh :smile: 
Though, I think it's worth keeping the bug fix separate from adding the new logging option.

**Comment by FedeDP** [comment]
>  Though, I think it's worth keeping the bug fix separate from adding the new logging option.

Yup; i had a brief private discussions with the maintainers and they told me to do as i want (about whether to make a PR on its own for the fix).
Nonetheless, i agree with you, let's keep this one and i'll rebase mine to drop the very first commit after this gets merged :)

File: pkg/logger/slog.go [hunk 1]
```diff
@@ -71,18 +71,22 @@ func initializeSlog(logOpts LogOptions, useStdout bool) {
 		writer = os.Stdout
 	}
 
+	var newDefaultLogger = DefaultSlogLogger
```
Comment (FedeDP) [inline pkg/logger/slog.go:74]: I don't think we need this assignment/copy.
We just need to:
* either avoid `newDefaultLogger` at all
* or just declare it as slog.Handler and use it afterward

right?

**Review by sayboras — APPROVED** [review]

File: pkg/logger/slog.go (hunk 1 above)
Comment (mann-ds) [reply pkg/logger/slog.go:74]: I've added it here to cover a case when `logFormat` is something else so that we don't have `DefaultSlogLogger` set to `nil` after the `switch` block because of any missing `case` branch(es).

Setting `*DefaultSlogLogger` in every `case` branch directly would also work here.

Comment (FedeDP) [reply pkg/logger/slog.go:74]: Yeah i see; no problem, we can leave it as-is :)

**Review by FedeDP — APPROVED** [review]

**Comment by mann-ds** [comment]
@FedeDP @sayboras can you please merge it if it's ready? I don't have permissions :smile:

**Comment by mtardy** [comment]
> @FedeDP @sayboras can you please merge it if it's ready? I don't have permissions 😄

I'm merging it, would have been cool to include the explanation of the why in the commit description but I'd say it's a fairly limited patch so that's okay.

**Review by mtardy — APPROVED** [review]

**Comment by FedeDP** [comment]
@mann-ds care to open a backport PR against v1.6? See https://github.com/cilium/tetragon/pull/4378#issuecomment-4016461266.
Thanks!

**Comment by mann-ds** [comment]
@FedeDP yeah, it would be great to backport both this PR and https://github.com/cilium/tetragon/pull/4734 to have consistent logs.

**Comment by mann-ds** [comment]
@mtardy is it possible to include this PR and https://github.com/cilium/tetragon/pull/4734 in the next release and publish it soon-ish? I saw 1.6.1 from yesterday here https://github.com/cilium/tetragon/releases/tag/v1.6.1, but couldn't find any mentions of these PRs or changes to the code in that tag [here](https://github.com/cilium/tetragon/blob/v1.6.1/pkg/logger/slog.go#L74-L84), unfortunately.

**Comment by mtardy** [comment]
> @mtardy is it possible to include this PR and #4734 in the next release and publish it soon-ish? I saw 1.6.1 from yesterday here https://github.com/cilium/tetragon/releases/tag/v1.6.1, but couldn't find any mentions of these PRs or changes to the code in that tag [here](https://github.com/cilium/tetragon/blob/v1.6.1/pkg/logger/slog.go#L74-L84), unfortunately.

Ah it slipped away sorry, if you didn't do any backport I don't think Federico or me did. Please do a backport on the v1.6 for the next release then if you want it.

**Comment by mann-ds** [comment]
> > @mtardy is it possible to include this PR and #4734 in the next release and publish it soon-ish? I saw 1.6.1 from yesterday here https://github.com/cilium/tetragon/releases/tag/v1.6.1, but couldn't find any mentions of these PRs or changes to the code in that tag [here](https://github.com/cilium/tetragon/blob/v1.6.1/pkg/logger/slog.go#L74-L84), unfortunately.
> 
> Ah it slipped away sorry, if you didn't do any backport I don't think Federico or me did. Please do a backport on the v1.6 for the next release then if you want it.

@mtardy @FedeDP I created a backport PR for the `v1.6` branch here: https://github.com/cilium/tetragon/pull/4907. Unfortunately, I don't have access to add backport labels there, can you please take a look?

**Comment by FedeDP** [comment]
Sure @mann-ds ! Thanks!
