### PR TITLE
fix: reject NotifyEnforcer kprobe action without an Enforcer

### LINKED ISSUE #4007: TracingPolicy: reject policies when NotifyEnforcers is specified but no Enforcer present
Currently, `TracingPolicy`'s with a `NotifyEnforcer` action but no corresponding `enforcers` clause will load without error. We should at least produce a warning here to warn the user that their intended enforcement actions will be absent without the `enforcers` clause.

### PR DESCRIPTION
**Pull request by dwindsor**
Fixes #4007 

### Changelog

```release-note
```

### Testing
This policy fails to load (it's missing `enforcers`):
```yaml
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "linux-ssh-key-config-deletion-detection"
  annotations:
    author: "Isovalent now part of Cisco"
spec:
  kprobes:
  - call: "security_path_unlink"
    syscall: false
    return: false
    tags: [ "attack.T1070.004", "attack.T1485", "attack.defense_evasion", "attack.impact" ]
    args:
    - index: 0
      type: "path"
    selectors:
    # System SSH keys/config files
    - matchArgs:
      - index: 0
        operator: "Prefix"
        values:
        - "/etc/ssh/ssh_host_"
        - "/etc/ssh/sshd_config"
        - "/etc/ssh/ssh_config"
      matchBinaries:
        - operator: "NotIn"
          values: ["/usr/bin/ssh-keygen", "/usr/sbin/sshd", "/usr/bin/dpkg"]
      matchActions:
      - action: NotifyEnforcer
 ```
 
Failure to load due to missing `enforcers`:
```
level=error msg="Failed to execute tetragon" error="policy handler 'tracing' failed loading policy 'linux-ssh-key-config-deletion-detection': NotifyEnforcer action specified, but spec contains no enforcers"
```

The same policy loads after adding a `enforcers`:
```yaml
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "linux-ssh-key-config-deletion-detection"
  annotations:
    author: "Isovalent now part of Cisco"
spec:
  enforcers:
    - calls:
      - security_path_unlink
  kprobes:
  - call: "security_path_unlink"
    syscall: false
    return: false
    tags: [ "attack.T1070.004", "attack.T1485", "attack.defense_evasion", "attack.impact" ]
    args:
    - index: 0
      type: "path"
    selectors:
    # System SSH keys/config files
    - matchArgs:
      - index: 0
        operator: "Prefix"
        values:
        - "/etc/ssh/ssh_host_"
        - "/etc/ssh/sshd_config"
        - "/etc/ssh/ssh_config"
      matchBinaries:
        - operator: "NotIn"
          values: ["/usr/bin/ssh-keygen", "/usr/sbin/sshd", "/usr/bin/dpkg"]
      matchActions:
      - action: NotifyEnforcer
```

Loaded successfully:

```
dave@cartman:~/src/github.com/cilium/tetragon$ sudo ./tetra tp list
ID   NAME                                      STATE     FILTERID   NAMESPACE   SENSORS                       KERNELMEMORY   MODE
1    linux-ssh-key-config-deletion-detection   enabled   0          (global)    __enforcer__,generic_kprobe   3.91 MB        enforce
```

### CODE REVIEW

File: pkg/sensors/tracing/policyhandler_linux.go [hunk 1]
```diff
@@ -126,6 +126,27 @@ func (h policyHandler) PolicyHandler(
 			"policy", tracingpolicy.TpLongname(policy),
 			"sensor", name,
 		)
+
+		// Check if any selector uses NotifyEnforcer action
```
Comment (kkourt) [inline pkg/sensors/tracing/policyhandler_linux.go]: The check makes sense to me. Can you add it to the `preValidateKprobes` function?
I think it's better to have all validation in a single place.

**Review by kkourt — CHANGES_REQUESTED** [review]
Thanks!

File: pkg/sensors/tracing/policyhandler_linux.go (hunk 1 above)
Comment (dwindsor) [reply pkg/sensors/tracing/policyhandler_linux.go]: Yeah makes sense! Thanks

File: pkg/sensors/tracing/generickprobe.go [hunk 2]
```diff
@@ -541,6 +541,29 @@ func preValidateKprobes(log logger.FieldLogger, kprobes []v1alpha1.KProbeSpec, l
 		return nil, fmt.Errorf("validateKprobeSpec: ksyms.KernelSymbols: %w", err)
 	}
 
+	// Check if any selector uses NotifyEnforcer action
+	hasNotifyEnforcer := false
+	for _, kprobe := range kprobes {
```
Comment (kkourt) [inline pkg/sensors/tracing/generickprobe.go:545]: How about using a [label](https://go.dev/ref/spec#Break_statements) to simplify breaking out of multiple loops?

**Review by kkourt — CHANGES_REQUESTED** [review]
Thanks!

Can you also please squash the changes form my original feedback into the relevant original commits? (`git rebase --interactive` using the `squash` and `fixup` actions should help).

**Comment by dwindsor** [comment]
qq @kkourt do you think it's worth adding a ci test for this? not sure if it's worth it (ie try to load a policy w/ notifyenforcers and no enforcers)

**Comment by kkourt** [comment]
> qq @kkourt do you think it's worth adding a ci test for this? not sure if it's worth it (ie try to load a policy w/ notifyenforcers and no enforcers)

I think trying to load a policy is a lot of effort to test this. If we want to test this, I would suggest to just write some unit tests for the `preValidateKprobes` function.

File: pkg/sensors/tracing/policyhandler_linux.go [hunk 3]
```diff
@@ -126,10 +126,12 @@ func (h policyHandler) PolicyHandler(
 			"policy", tracingpolicy.TpLongname(policy),
 			"sensor", name,
 		)
-		validateInfo, err := preValidateKprobes(log, spec.KProbes, spec.Lists)
+
```
Comment (mtardy) [inline pkg/sensors/tracing/policyhandler_linux.go]: nit: whiteline changes

File: pkg/sensors/tracing/policyhandler_linux.go [hunk 4]
```diff
@@ -126,10 +126,12 @@ func (h policyHandler) PolicyHandler(
...
+		validateInfo, err := preValidateKprobes(log, spec.KProbes, spec.Lists, spec.Enforcers)
 		if err != nil {
 			return nil, fmt.Errorf("validation failed: %w", err)
 		}
+
```
Comment (mtardy) [inline pkg/sensors/tracing/policyhandler_linux.go]: here as well

File: pkg/sensors/tracing/generickprobe.go (hunk 2 above)
Comment (olsajiri) [reply pkg/sensors/tracing/generickprobe.go:545]: we do have already some of selectors.Has* functions, we could add it there
also we do have `func HasSigkillAction(kspec *v1alpha1.KProbeSpec) bool` maybe we could add generic `HasAction` helper

Comment (dwindsor) [reply pkg/sensors/tracing/generickprobe.go:545]: Thanks just added `HasNotifyEnforcerAction`, I agree that `HasAction` would be useful but could we do that in another PR?
